name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-28"
          sdkmanager "build-tools;28.0.3"

      - name: Build APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RazaqKeyboard-debug
          path: app/build/outputs/apk/debug/app-debug.apk
